### ISSUE TITLE
phrasing about SD and ABM

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#102]
Hi @gidden - I was going through some suggestions made by Erich for the Fundamentals paper and I ran accross one that I didn't feel like I could handle on my own. 
The paragraph in question is in the impl.tex file:

```
Furthermore, the \gls{ABM} paradigm is superior to the system dynamic approach used in
current simulators.
System dynamics is a popular approach for modeling nuclear fuel cycles
\cite{jacobson_vision_2009,van_den_durpel_daness_2009,guerin_impact_2009,guerin_benchmark_2009}.
Formally however, system dynamics models are simply a strict subset of agent-based models
\cite{macal_agent-based_2010}.
That is, any system dynamics model can be translated
into an agent-based model. Furthermore, because agent-based
techniques can provide a richer model than can system dynamics, they enable the
broadest range of simulations in a generic fashion.
```

The comment from Erich is:
```
I think this paragraph requires substantiation... the claim was made that ABM is superior to SD, 
but not (to my mind) proved.  ABM encompasses SD but that doesn't make it better.  To 
substantiate this and the 'richer model' claim, suggest developing specific examples of things 
ABM can do that SD can't
```

I would suggest this simple change:

The final sentence of the paragraph:
```
Furthermore, because agent-based
techniques can provide a richer model than can system dynamics, they enable the
broadest range of simulations in a generic fashion.
```
could become:
```
Therefore, they enable a broader range of simulations in a more generic fashion.
```

What do you think?

**Comment by gidden** [comment]
This portion was written originally by @scopatz, is memory serves. I agree
that it is a *strong* claim; however, the claim is derived from the cited
paper (Macal, et. al.). A semi-formal proof exists in the paper. I think
you're proposed fix is fine. Would you like me to make the commit and PR it?

On Mon, Mar 2, 2015 at 11:58 AM, Katy Huff <notifications@github.com> wrote:

> Assigned #102 <https://github.com/cyclus/fundamentals-paper/issues/102>
> to @gidden <https://github.com/gidden>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/102#event-244549377>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by katyhuff** [comment]
Oh, sorry, thought it was you. I'm happy to make the change. Thanks for the
speedy feedback!

On Mon, Mar 2, 2015 at 10:05 AM, Matthew Gidden <notifications@github.com>
wrote:

> This portion was written originally by @scopatz, is memory serves. I agree
> that it is a *strong* claim; however, the claim is derived from the cited
> paper (Macal, et. al.). A semi-formal proof exists in the paper. I think
> you're proposed fix is fine. Would you like me to make the commit and PR
> it?
>
> On Mon, Mar 2, 2015 at 11:58 AM, Katy Huff <notifications@github.com>
> wrote:
>
> > Assigned #102 <https://github.com/cyclus/fundamentals-paper/issues/102>
> > to @gidden <https://github.com/gidden>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/cyclus/fundamentals-paper/issues/102#event-244549377
> >.
> >
>
>
>
> --
> Matthew Gidden
> Ph.D. Candidate, Nuclear Engineering
> The University of Wisconsin -- Madison
> Ph. 225.892.3192
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/102#issuecomment-76764611>
> .
>



-- 
http://katyhuff.github.com

**Comment by scopatz** [comment]
From checking the history, I did not write this originally.  My edits to this file have relatively minor.  Though I do agree that the wording is too strong.

**Comment by katyhuff** [comment]
cool! Fixed now. Thanks both!

On Mon, Mar 2, 2015 at 10:11 AM, Anthony Scopatz <notifications@github.com>
wrote:

> From checking the history, I did not write this originally. My edits to
> this file have relatively minor. Though I do agree that the wording is too
> strong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/102#issuecomment-76766259>
> .
>



-- 
http://katyhuff.github.com
