### ISSUE TITLE
Reviewer 1: Comment 5: Less Marketing Talk

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#118]
> IB Motivation, 1st §: please provide scientific grounds for the claims in the first paragraph. Virtually all simulators developed by authoritative labs/companies do have the possibility to compare various nuclear energy system options with varying innovative technologies as part of these systems. The main question is how simulators can address the flurry of questions being addressed by users. The sentence "lower the barrier ... without those innovative concepts" is more 'marketing-talk than truly a scientific analysis as such. None of the simulators today, neither CYCLUS, can address the variety of questions to be addressed by such simulators and especially in industrial context, these simulators need increasingly detailed capabilities and validation to remain thrustworthy in their application.

- [ ] Using our various motivating documents (such as the Next Gen Fuel Cycle Simulator Functions and Requirements doc) provide the scientific grounds for the clains. 
- [x] Capture the sentiment in the "lower the barrier... without those innovative concepts" sentence in a more scientific way (see moose team paper for an example of noting the importance of usability)
- [ ] Consider citing reproducibility/open-science/transparency papers in a concise way in order to bolster the message captured by these statements.
- [x] Emphasize multiple fidelities capability in cyclus. This capability **clearly** has not been successfully communicated to Reviewer 1, who seems to believe "None of the simulators today, neither CYCLUS, can address the variety of questions to be addressed by such simulators"

**Comment by gidden** [comment]
Two primary comments:

0. I absolutely think we should be highlighting the repoducibility of analysis results as a major issue with other codes as well as a lack of transparency of their internal methods/algorithms/etc.  
0. I would actually say that, as it stands, Cyclus (with Cycamore) can not address many of "the variety of questions to be addressed by such simulators". Yet. What Cyclus enables is a platform for quickly developing the capability needed to answer these questions. I think we want to highlight the "fast development iteration" rather than claiming (without backing up) that we can answer certain questions.

**Comment by rwcarlsen** [comment]
I agree with @gidden.  And on his 2nd point - I wrote a fleet-based
continuous material flow reactor archetype in 1 day! - and it can be
swapped in/out with other archetypes trivially.

**Comment by gonuke** [comment]
I'm not sure how to state it in a way that is objective/citable, but I think one of the outcomes of poor cross-tool reproducibility is a credibility gap: consumers of the output can easily believe that if they just wait for the next tool, they'll get a different answer.  (Maybe this is not helpful....)

**Comment by katyhuff** [comment]
@gonuke @gidden @rwcarlsen I agree with all of you!

**Comment by katyhuff** [comment]
I made an attempt toward these, but have decided to handle the following two parts of this to other issues (where they are also mentioned):
- Consider citing reproducibility/open-science/transparency papers in a concise way in order to bolster the message captured by these statements.
-Using our various motivating documents (such as the Next Gen Fuel Cycle Simulator Functions and Requirements doc) provide the scientific grounds for the claims.
