### ISSUE TITLE
Reviewer 2: Comment 2: Simplify software talk?

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#120]
> I suggest that the first pages referring to computer software should be simplified.

- [ ] Read through the first few pages. Where there is software jargon, consider replacing it with not-jargon. See how much can be done without sacrificing technical merit.

**Comment by gidden** [comment]
The technical jargon I see is

- open source
- "modularity" (maybe?)
- clusters
- DLLs

I think each of these are important. We do have some conceptual overlap between modularity and DLLs which we could probably trim.
