### ISSUE TITLE
Reviewer 2: Comment 5: Nontechnical Criticism

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#123]
> page 1: "However, current fuel cycle simulators rely on closed platforms and inflexible architectures which exhibit three main failure modes. First, they discourage targeted contribution and collaboration among experts. Next, they hobble efforts to directly compare modeling methodologies. Finally, they over-specialize, rendering most tools applicable to only a subset of desired simulation fidelities, scales, and applications.", these sentences have nothing to do in a technical paper. There are numerous technical aspects in the fuel cycle which deserve attention and it would be nice to have them listed somewhere.

- [x] The first is the concern that citing the limitations of other tools does not belong in a technical paper. Discussion of the capability gaps of related work is an essential part of literature review in a technical paper. However, to approach it in a positive way, **we should rephrase these sentences in terms of the way that Cyclus fills these gaps instead.** These capabilities are the key elements of Cyclus functionality demonstrated later in the paper - therefore it is essential to mention their absence in the field.
- [ ] The second concern is that the specific technical requirements of a fuel cycle simulator are not discussed. We should respond to the reviewer by pointing out that we do see the listed capabilities as technical. The capacity for customizability by experts, ability to use Cyclus to directly compare modeling methodologies, and the capability to flexibly model numerous fidelities power . However, **we should remedy this perceived issue with a paragraph concerning the Next Generation Fuel Cycle Simulator Functions and Requirements arrived at by the DOE effort on that topic.**

**Comment by gidden** [comment]
Maybe I'm reading the issue wrong, but what are the two bullet points suggesting as far as work/edits?

**Comment by katyhuff** [comment]
Sorry, I wrote them in past tense in the doc then copied them without changing the tense.The solutions are noted here, but have not been done yet. I'll edit the issue and change the tense.
