### ISSUE TITLE
Reviewer 2: Comment 6: Judgmental language

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#124]
> page 1&2: "To date, current tools are often rigid rather than flexible, fleet-based rather than discrete, or privately distributed rather than open source.": it is always easier to denigrate old tools than illustrate the merits of a new one. This is not really necessary for the understanding of the note.

- [ ] (robert c) Perhaps we could reword or remove the first point in the trio, but the last two points are technical and/or significantly unique aspects of Cyclus.  See the response to reviewer 1 about individual vs fleet based. (# )

**Comment by gidden** [comment]
There are a number of issues regarding our criticism of other codes. Perhaps we could group them under a submilestone or separate issue?

**Comment by katyhuff** [comment]
Went with "To date, current tools are often fleet-based rather than discrete and privately distributed rather than open source. These choices both present challenges to modeling fidelity, generality, efficiency, robustness, and scientific transparency."
