### ISSUE TITLE
Reviewer 2: Comment 10: Cyclopts simulation details

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#126]
> page 9: "Cyclopts [26], a proof of principle design and implementation of a CYCLUS-enabled application on such a large computer system, uses UW-Madison's HTCondor HTC infrastructure to perform sensitivity studies.": please illustrate what kind of sensitivity studies, you are able to perform.

- [ ] Do exactly as suggested. Note (and potentially provide a plot) previous studies. Cite past presentation and work on this topic as a primary resource. Avoid going into great detail, but provide sufficient detail and citations to satisfy the curious reader.

**Comment by gidden** [comment]
While sensitivity studies were performed, they are not likely the sensitivity studies expected in a NFC context. I'll mull this over and think about the best way to clarify/expound.

**Comment by mbmcgarry** [comment]
Though the sensitivity studies that have been performed may not be those expected, it still might be sufficient to discuss them and possibly include a plot.  It will at least clarify what has and has not been done with Cyclus thus far and give the audience a better sense of the fundamental (non-physics) features of Cyclus.


On May 11, 2015, at 6:37 PM, Matthew Gidden <notifications@github.com<mailto:notifications@github.com>> wrote:


While sensitivity studies were performed, they are not likely the sensitivity studies expected in a NFC context. I'll mull this over and think about the best way to clarify/expound.
