### ISSUE TITLE
Reviewer 2: Comment 17: Eating Pudding 

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#129]
> "The proof of the pudding is the eating", it would be wise for the authors to participate to benchmark studies being conducted at the OECD: "Nuclear science > Working Party on Scientific Issues of the Fuel Cycle (WPFC) > "The Effects of the Uncertainty of Input Parameters on Nuclear Fuel Cycle Scenario Studies ". The benchmark treats realistic Nuclear Fuel Cycle Scenario Studies and codes like COSI, VISION and FAMILY21 (cited in the article) can model systems (stocks, factories, storage facilities, reactors) with different characteristics but also factories at different scales ranging from very macroscopic modeling of a park to a very fine modeling, facility by facility, year by year. The objects modeled in the example (page 33) can be modeled by COSI, VISION and FAMILY21 (cited in the article).

- [ ] This will be partially solved with a solution to #119
- [ ] Furthermore, current benchmarks in the works (namely FCO) should be mentioned
- [ ] A desire to participate in further benchmarks should be mentioned.
- [ ] ~~For good measure, we could (and probably should, in any case) reproduce our previous inpro simulation.~~

**Comment by gidden** [comment]
I think that this is not a comment that can really be directly addressed in this paper other than #119 and mentioning ongoing work and future desired inclusion. 

It would be a great ANS paper (for a new grad student perhaps?) to now run through the INPRO cases with the current Cyclus and Cycamore at 1.3. It shouldn't be too difficult^TM, and more of a scenario creation/analysis workload with minimal-to-no archetype development.
