### ISSUE TITLE
CI description is no longer current

### ISSUE THREAD

**Issue by gidden** [cyclus/fundamentals-paper#138]
We now use CircleCI. At the time of writing, we were still on Polyphemus. And _at the time_ of the 1.0 release we were as well.

**Comment by gidden** [comment]
Ideas/thoughts @katyhuff, @scopatz, @gonuke?

**Comment by gidden** [comment]
If there is a suggestion on the table to revamp the QA section, perhaps we can simply mention that Cyclus and its ecosystem is under CI.

**Comment by katyhuff** [comment]
Ah, forgot about that. Let's just update it to reflect the current state. I
think most other things (such as names of facility classes and such) have
been updated to reflect the current state.

On Tue, Sep 8, 2015 at 8:56 AM, Matthew Gidden <notifications@github.com>
wrote:

> If there is a suggestion on the table to revamp the QA section, perhaps we
> can simply mention that Cyclus and its ecosystem is under CI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/138#issuecomment-138608299>
> .
>



-- 
http://katyhuff.github.com

**Comment by katyhuff** [comment]
Fixed by #139 and #140 .
