### ISSUE TITLE
Scopatz Read-through

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#44]
Each author should read through the paper once (seems crazy? it's not! Do you really want to be an author on a paper with an entire section on how "superman bubblegum sticks to the roof of your mouth"? Don't let that be you!!)

Please consider the following questions during your read-through of the paper and consider the following questions. Push changes and/or make pull requests accordingly. 

- [ ] Does the introduction draw the reader in?
- [ ] Are all sentences clear?
- [ ] Does the conclusion summarize the topic?
- [ ] Is the outline coherent?
- [ ] Are there any missing sections or essential topics left unaddressed?
- [ ] Do any statements require additional citation?
- [ ] Would additional diagrams or plots clarify any discussion?
- [ ] Does the paper address the focus areas of the target journal?

**Comment by katyhuff** [comment]
@scopatz - I think you pretty much completed this a few months ago. I had left it open because your review appeared in the form of broader comments rather than detailed changes. Those have since been addressed (by @opotowsky , mostly), so I'm going to close this issue. If you'd like to do more review, please don't hesitate to do so, of course. Submit any changes by pull request. Thanks!

**Comment by scopatz** [comment]
I'll see if I can't sneak some time later next week.
