### ISSUE TITLE
Wilson Read-through

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#46]
Each author should read through the paper once (seems crazy? it's not! Do you really want to be an author on a paper with an entire section on how "superman bubblegum sticks to the roof of your mouth"? Don't let that be you!!)

Please consider the following questions during your read-through of the paper and consider the following questions. Push changes and/or make pull requests accordingly. 

- [ ] Does the introduction draw the reader in?
- [ ] Are all sentences clear?
- [ ] Does the conclusion summarize the topic?
- [ ] Is the outline coherent?
- [ ] Are there any missing sections or essential topics left unaddressed?
- [ ] Do any statements require additional citation?
- [ ] Would additional diagrams or plots clarify any discussion?
- [ ] Does the paper address the focus areas of the target journal?

**Comment by katyhuff** [comment]
@gonuke . I appreciated your thematic comments on this paper. I have left this issue open because your review appeared in the form of broader comments rather than detailed changes. Those have since been addressed to the best of my ability (https://github.com/cyclus/fundamentals-paper/pull/69). 

I would like to send a pre-submission inquiry to NT by one week from today. If you would like to take a moment to do a full read-through of the paper at this time, now is the appropriate time to do that. If you feel you have already given the paper sufficient review and you approve of it (pending minor edits forthcoming this week) please feel free to close this issue.

**Comment by gonuke** [comment]
The paper is really in great shape!!!  Thanks for all of your hard work on pulling this together.

All of my comments from this read through have been logged in specific pull-requests and issues.

**Comment by katyhuff** [comment]
Whoo!! I'm so glad you think so. I'll work through the rest of your PRs
very shortly. Thanks!!!!

On Sun, Feb 22, 2015 at 11:58 AM, Paul Wilson <notifications@github.com>
wrote:

> The paper is really in great shape!!! Thanks for all of your hard work on
> pulling this together.
>
> All of my comments from this read through have been logged in specific
> pull-requests and issues.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/46#issuecomment-75454257>
> .
>



-- 
http://katyhuff.github.com
