### ISSUE TITLE
Cluster-Ready Software

### ISSUE THREAD

**Issue by mbmcgarry** [cyclus/fundamentals-paper#58]
Paragraph about Cyclopts and parallelization does not sufficiently distinguish between the test on 10^4 jobs and the 'full Cyclus simulation' test on 10^3 machines with 10^5 simulations.  If this second example is using the 'full' simulation, then what did the first example use?

**Comment by katyhuff** [comment]
@gidden @rwcarlsen ... I'm pinging you because you together are probably expert-level-qualified to finalize this section (which has a bunch of todos). I'm assigning this to @rwcarlsen , but please please feel free to reassign appropriately. 
Thanks so much!

**Comment by katyhuff** [comment]
@gidden , I'm going to reassign this to you since you wrote the original text for this section, I believe. I imageine you'll handle this in your readthrough anyway (there's a red TODO) in that section. 

Thanks!!!

**Comment by katyhuff** [comment]
completed with @gidden merge #93 .
