### ISSUE TITLE
Demonstration - reference to multi-pass recycle case

### ISSUE THREAD

**Issue by mbmcgarry** [cyclus/fundamentals-paper#62]
The reference to the limitations of the presented example w.r.t a multi-pass recycle case is ambiguous.  You should clarify why nucleide flows are reasonable for this example but not multi-pass and then comment on the fact that Cyclus can in fact handle multi-pass properly by changing the configuration of the simulation.

**Comment by katyhuff** [comment]
ping @rwcarlsen , wanted to put this back on your radar. Trying to finalize this paper. Let me know if I can do anything to help expedite it. Thanks so much!

**Comment by rwcarlsen** [comment]
see #72 - should address a good chunk of this.

**Comment by katyhuff** [comment]
Thanks so much! I'm in the middle of some stuff this afternoon but will
definitely look all this over this evening.

On Thu, Feb 5, 2015 at 12:11 PM, Robert Carlsen <notifications@github.com>
wrote:

> see #72 <https://github.com/cyclus/fundamentals-paper/pull/72> - should
> address a good chunk of this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/62#issuecomment-73117588>
> .
>



-- 
http://katyhuff.github.com

**Comment by katyhuff** [comment]
M eyes are weary. I caught some typos, but my eyes are weary, so I'm not
giving it the most subtle reading. I'll give a look with fresh eyes in the
morning. Thanks for your patience.


On Thu, Feb 5, 2015 at 1:10 PM, Katy Huff <katyhuff@gmail.com> wrote:

> Thanks so much! I'm in the middle of some stuff this afternoon but will
> definitely look all this over this evening.
>
> On Thu, Feb 5, 2015 at 12:11 PM, Robert Carlsen <notifications@github.com>
> wrote:
>
>> see #72 <https://github.com/cyclus/fundamentals-paper/pull/72> - should
>> address a good chunk of this.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/cyclus/fundamentals-paper/issues/62#issuecomment-73117588>
>> .
>>
>
>
>
> --
> http://katyhuff.github.com
>



-- 
http://katyhuff.github.com

**Comment by katyhuff** [comment]
Closed! Thanks @rwcarlsen !
