### ISSUE TITLE
TODO about potential diagram

### ISSUE THREAD

**Issue by katyhuff** [cyclus/fundamentals-paper#79]
Hi @rwcarlsen . Previous reviewers of the fundamentals paper have noted that the materials tracking section might be improved by a diagram summarizing the material tracking and caching paradigm. Does such an image exist, or would you be willing to create one?

If so, please add one in place of the TODO in impl.tex that says "do we want a diagram helping show this composition caching?" 

If not, please let me know and remove the TODO.

Of course, please submit any changes via pull request.

Thank you!!

**Comment by rwcarlsen** [comment]
I'll take a crack tomorrow.

**Comment by katyhuff** [comment]
nice! Thanks @rwcarlsen !!
