### ISSUE TITLE
QA section has too much detail

### ISSUE THREAD

**Issue by gonuke** [cyclus/fundamentals-paper#84]
I think the QA section has far too much detail (6 pages out of 37 in the draft I read).  It is certainly, important but I think that for the audience in question, we only need to provide confidence that we are doing it right, not explain the full QA protocol in detail.

I am happy to take a crack at revising it, but felt it was potentially a step to far without consulting first with the original authors, whoever they are. (@scopatz @katyhuff @opotowsky ?)

**Comment by gidden** [comment]
+1 on this suggestion

On Sun, Feb 22, 2015 at 1:34 PM, Paul Wilson <notifications@github.com>
wrote:

> I think the QA section has far too much detail (6 pages out of 37 in the
> draft I read). It is certainly, important but I think that for the audience
> in question, we only need to provide confidence that we are doing it right,
> not explain the full QA protocol in detail.
>
> I am happy to take a crack at revising it, but felt it was potentially a
> step to far without consulting first with the original authors, whoever
> they are. (@scopatz <https://github.com/scopatz> @katyhuff
> <https://github.com/katyhuff> @opotowsky <https://github.com/opotowsky> ?)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/84>.
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by katyhuff** [comment]
Yeah, I think that makes lots of sense. @gonuke , @gidden , can you coordinate a decision on who wants to tackle it? (Perhaps assign yourself to this issue if you want to be the one taking a crack at it in the short term) If neither of you has a chance to do this, I can pass through and cut it down later this week.

**Comment by gonuke** [comment]
What's the authorship history of this section?  (git log/blame are not particularly helpful)

**Comment by katyhuff** [comment]
@scopatz wrote it. Then @opotowsky edited a bit. Then, when I edited it (just a bit), my text editor preferences removed a bunch of trailing whitespace and whatnot... unfortunately stomping all over the git blame.

**Comment by gidden** [comment]
I *believe* @scopatz was the primary author. I really like the writing here
and would prefer if the original author tackled it so I (or others) don't
venture too far. If the author is too busy, I can take a look.

On Sun, Feb 22, 2015 at 2:38 PM, Paul Wilson <notifications@github.com>
wrote:

> What's the authorship history of this section? (git log/blame are not
> particularly helpful)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/84#issuecomment-75456365>
> .
>



-- 
Matthew Gidden
Ph.D. Candidate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
```latex
\[busy(t) = lim_{h\to 0} \frac{1}{h}\]
```

**Comment by katyhuff** [comment]
understood. I'll just pull it, then.


On Mon, Mar 2, 2015 at 1:50 PM, Anthony Scopatz <notifications@github.com>
wrote:

> \[busy(t) = lim_{h\to 0} \frac{1}{h}\]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/fundamentals-paper/issues/84#issuecomment-76833607>
> .
>



-- 
http://katyhuff.github.com
