### ISSUE TITLE
Missing branch in git-flow diagram

### ISSUE THREAD

**Issue by gonuke** [cyclus/fundamentals-paper#86]
Notwithstanding earlier queries about whether or not this is too much detail....

The last conditional on the gitflow diagram is missing a path to follow if the review does not pass.

**Comment by katyhuff** [comment]
good catch. I'll fix it.

**Comment by gonuke** [comment]
I'd wait until we decide whether or not the image is necessary/appropriate at all...

**Comment by katyhuff** [comment]
It was an easy fix. Fixed in #90.
