### ISSUE TITLE
DRE exchange graphs vs. material flow graphs

### ISSUE THREAD

**Issue by gonuke** [cyclus/fundamentals-paper#87]
Figures 6 & 7 show the material flow under 2 different scenarios, but do not show how the possible DRE paths change under those  scenarios.  In particular, I expect that the repo is always willing to take spent_fuel in addition to waste, but just doesn't because the separations competes favorably for it.

I recommend either:
1. adding text to clarify why these figures don't show the spent_fuel->repo relationship
2. adding figures that show the possible relationships, including possibly a 0 kg flow along the spent_fuel -> repo paths

**Comment by rwcarlsen** [comment]
I vote 2.

**Comment by katyhuff** [comment]
2 would be great. Is that something that you might be able to do with cyan, @rwcarlsen ?

**Comment by rwcarlsen** [comment]
Cyan just generates graphviz dot files.  It would probably be easier to just tweak them by hand for this particular case.
