### ISSUE TITLE
Clarify discussion of exclusive trades

### ISSUE THREAD

**Issue by gonuke** [cyclus/fundamentals-paper#89]
The exclusivity of trades is introduced in a paragraph about bids, suggesting that it is more closely related to bids than to requests.  My internal bias is the opposite, although, in fact, I imagine that both requests and bids can be constrained as exclusive.  (I should probably know this!)

https://github.com/cyclus/fundamentals-paper/blob/master/fundamentals/impl.tex#L403

We can either introduce exclusivity with the paragraph on requests, or give it it's own paragraph.

**Comment by katyhuff** [comment]
Good point. I'll assign @gidden, DRE expert-in-charge, to this one.
