### ISSUE TITLE
Add section that elaborates on contributions

### ISSUE THREAD

**Issue by gonuke** [cyclus/fundamentals-paper#91]
Given the size of the author list (I know, we're not anything like high energy physicists yet), I think we should include a section that elaborates on the specific contributions of each author.  There have been recent proposals along these lines (e.g. http://credit.casrai.org/proposed-taxonomy/).

**Comment by katyhuff** [comment]
That sounds neat, but somewhat tricky. Perhaps this can be merged into the (currently nonexistent) acknowledgements section). Perhaps we can about this at this week's dev meeting.

**Comment by gonuke** [comment]
See also: http://blog.wellcome.ac.uk/2014/04/17/beyond-authorship/

Yes - I'm sure it will be tricky - but I think a taxonomy like this adds some important structure to otherwise tricky conversations anyway.

**Comment by katyhuff** [comment]
Ok, I'll take this on. By the time of the cyclus-dev meeting, I'll try to have a (no doubt very imperfect) draft.

**Comment by katyhuff** [comment]
Ok, after thinking and reading, I take back my volunteerism. A draft can't come from just one person. I think it needs to come about from : 
1) Self reported assessments of where folks feel they fit in the taxonomy
2) and a discussion about how to present that in the paper (which maybe you're a better person to lead @gonuke , if you're willing?)

**Comment by scopatz** [comment]
Hi all, after reading through @gonuke's links and thinking on this over the weekend, I am sceptical that this can be executed in a fair way here. It seems that most people would fit in most categories, which undermines the purpose of the categories. I also don't know what the conflict resolution mechanism would be if person X felt like they were unjustly left out category A - even though they are rightly in categories B, C, D, ...  Also, how would we resolve the situation where person Y wants to unwilliningly remove person X from a category?

I am all for trying out alternative publication structures, but perhaps this paper isn't the correct venue to start with. I'd love it if we tried this on a conference proceeding or two and knew the pitfalls and learned how to address them.

**Comment by scopatz** [comment]
Everyone should feel free to contact me individually if you have any questions about my concerns :).
