### ISSUE TITLE
No previous mention of three demonstration archetypes

### ISSUE THREAD

**Issue by gidden** [cyclus/fundamentals-paper#95]
We mention archetypes in two places: Tables 1 and 3. Then the simulations example cites cycamore::Reactor, cycamore::Fab, and cycamore::Separations. First, none of these are in cycamore proper. Second, they have not been mentioned until this section. I think the easiest course of action is to add descriptions in Table 3 and remove the cycamore namespace in the text. I know we discussed this before as a group, but I don't think any resolution was found.

**Comment by katyhuff** [comment]
The thing we discussed as a group was that these items were going to end up in Cycamore before the upcoming release... which solves at least that part of it. Was that what you recall, @rwcarlsen ?
